//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warsha.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mabeaat
    {
        public int id { get; set; }
        public int Prod_id { get; set; }
        public System.DateTime date { get; set; }
        public string note { get; set; }
        public decimal Quantity { get; set; }
        public decimal Total_price { get; set; }
        public decimal money_done { get; set; }
        public decimal money_res { get; set; }
        public int togarr_id { get; set; }
        public int Status_id { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual MAbeaat_Status MAbeaat_Status { get; set; }
        public virtual Togarrr Togarrr { get; set; }
    }
}
