//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warsha.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FactorManagmentEntities : DbContext
    {
        public FactorManagmentEntities()
            : base("name=FactorManagmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Good> Goods { get; set; }
        public virtual DbSet<Mabeaat> Mabeaats { get; set; }
        public virtual DbSet<Masrofat> Masrofats { get; set; }
        public virtual DbSet<Moshtriat> Moshtriats { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Togarrr> Togarrrs { get; set; }
        public virtual DbSet<MAbeaat_Status> MAbeaat_Status { get; set; }
        public virtual DbSet<Togaar_type> Togaar_type { get; set; }
    }
}
