//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warsha.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moshtriat
    {
        public int id { get; set; }
        public int Goods_id { get; set; }
        public System.DateTime Date { get; set; }
        public string note { get; set; }
        public decimal quantity { get; set; }
        public Nullable<decimal> Total_price { get; set; }
        public Nullable<decimal> pr { get; set; }
    
        public virtual Good Good { get; set; }
    }
}
