//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warsha.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Togarrr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Togarrr()
        {
            this.Mabeaats = new HashSet<Mabeaat>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public int type_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mabeaat> Mabeaats { get; set; }
        public virtual Togaar_type Togaar_type { get; set; }
    }
}
